version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: eppostgres
  wallet-app:
    image: hatemhobbies/wallet-service:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      -  POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - /data/walletservice
    container_name: walletservice
